
services:
  - type: web
    name: sanaly-aqtau-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        value: 7070979165:AAGJgFIkGpePUMLZQUlDlO2vfqMESdWPM-I
